services:
  - type: web
    name: sales-portal-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DB_NAME
        fromDatabase:
          name: sales-portal-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: sales-portal-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: sales-portal-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: sales-portal-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: sales-portal-db
          property: port

databases:
  - name: sales-portal-db
    databaseName: sales_portal
    plan: free 